apiVersion: v1
kind: Namespace
metadata:
  name: vulnerable-lab
  labels:
    app.kubernetes.io/name: juice-shop
    app.kubernetes.io/part-of: secure-kube-ops
    securekubeops.io/purpose: vulnerable-lab
