{
 "title": "SecureKubeOps Runtime Security - Trivy Operator",
 "description": "Runtime security dashboard for SecureKubeOps using Trivy Operator metrics: vulnerabilities, Kubernetes misconfigurations, exposed secrets, RBAC assessment and infra assessment.",
 "tags": [
  "securekubeops",
  "trivy-operator",
  "runtime-security",
  "kubernetes"
 ],
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Entorno",
    "label": "Namespace",
    "query": {
     "query": "label_values(trivy_image_vulnerabilities,namespace)"
    }
   },
   {
    "name": "Severity",
    "label": "Severity",
    "query": "Critical, High, Medium, Low, Unknown"
   }
  ]
 },
 "panels": [
  {
   "title": "Quick Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Number and Type of Security Issues",
     "type": "stat",
     "description": "Total number by type of security issues identified in the cluster",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 1 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(trivy_image_vulnerabilities{namespace=~\"$Entorno\", severity=~\"$Severity\"}) or on() vector(0)",
       "legendFormat": "Vulnerabilities"
      },
      {
       "expr": "sum(trivy_resource_configaudits{namespace=~\"$Entorno\", severity=~\"$Severity\"}) or on() vector(0)",
       "legendFormat": "Misconfiguration"
      },
      {
       "expr": "sum(trivy_clusterrole_clusterrbacassessments{namespace=~\"$Entorno\",severity=~\"$Severity\"}) or on() vector(0)",
       "legendFormat": "RBAC Assessment"
      },
      {
       "expr": "count(trivy_infraassessments_info{namespace=~\"$Entorno\", severity=~\"$Severity\"}) or on() vector(0)",
       "legendFormat": "InfraAssessments"
      },
      {
       "expr": "sum(trivy_image_exposedsecrets{namespace=~\"$Entorno\", severity=~\"$Severity\"}) or on() vector(0)",
       "legendFormat": "Exposed Secrets"
      }
     ]
    }
   ]
  },
  {
   "title": "Vulnerabilities",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Severity Breakdown of all Vulnerabilities",
     "type": "stat",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(trivy_image_vulnerabilities{severity=\"Critical\",namespace=~\"$Entorno\"}) or on() vector(0)",
       "legendFormat": "Critical"
      },
      {
       "expr": "sum(trivy_image_vulnerabilities{severity=\"High\",namespace=~\"$Entorno\"}) or on() vector(0)",
       "legendFormat": "High"
      },
      {
       "expr": "sum(trivy_image_vulnerabilities{severity=\"Medium\",namespace=~\"$Entorno\"}) or on() vector(0)",
       "legendFormat": "Medium"
      },
      {
       "expr": "sum(trivy_image_vulnerabilities{severity=\"Low\",namespace=~\"$Entorno\"}) or on() vector(0)",
       "legendFormat": "Low"
      },
      {
       "expr": "sum(trivy_image_vulnerabilities{severity=\"Unknown\",namespace=~\"$Entorno\"}) or on() vector(0)",
       "legendFormat": "Unknown"
      }
     ]
    },
    {
     "title": "Number of Vulnerabilities by namespace",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 164 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(trivy_image_vulnerabilities {namespace=~\"$Entorno\",severity=~\"$Severity\",}) by (namespace)  ",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total vulnerabilities by severity in selected namespace(s)",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 164 },
     "targets": [
      {
       "expr": "sum(trivy_image_vulnerabilities{namespace=~\"$Entorno\",severity=~\"$Severity\"}) by (severity)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Vulnerability by Image",
     "type": "table",
     "gridPos": { "h": 14, "w": 24, "x": 0, "y": 175 },
     "targets": [
      {
       "expr": "sum(trivy_image_vulnerabilities{namespace=~\"$Entorno\",severity=\"Critical\"}) by (image_repository,image_tag)"
      },
      {
       "expr": "sum(trivy_image_vulnerabilities{namespace=~\"$Entorno\",severity=\"High\"}) by (image_repository,image_tag)"
      },
      {
       "expr": "sum(trivy_image_vulnerabilities{namespace=~\"$Entorno\",severity=\"Medium\"}) by (image_repository,image_tag)"
      },
      {
       "expr": "sum(trivy_image_vulnerabilities{namespace=~\"$Entorno\",severity=\"Low\"}) by (image_repository,image_tag)"
      },
      {
       "expr": "sum(trivy_image_vulnerabilities{namespace=~\"$Entorno\",severity=\"Unknown\"}) by (image_repository,image_tag)"
      }
     ]
    },
    {
     "title": "Detailed CVE vulnerabilities in All Namespace(s)",
     "type": "table",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 189 },
     "targets": [
      {
       "expr": " sum by (installed_version, vuln_id, vuln_title, severity, vuln_score, image_repository,image_registry,image_tag, resource, fixed_version, namespace) (trivy_vulnerability_id{namespace=~\"$Entorno\",severity=~\"$Severity\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "Misconfiguration",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Severity Breakdown of all Misconfiguration",
     "type": "stat",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(trivy_resource_configaudits{namespace=~\"$Entorno\",severity=\"Critical\"}) or on() vector(0)",
       "legendFormat": "Critical"
      },
      {
       "expr": "sum(trivy_resource_configaudits{namespace=~\"$Entorno\",severity=\"High\"}) or on() vector(0)",
       "legendFormat": "High"
      },
      {
       "expr": "sum(trivy_resource_configaudits{namespace=~\"$Entorno\",severity=\"Medium\"}) or on() vector(0)",
       "legendFormat": "Medium"
      },
      {
       "expr": "sum(trivy_resource_configaudits{namespace=~\"$Entorno\",severity=\"Low\"}) or on() vector(0)",
       "legendFormat": "Low"
      },
      {
       "expr": "sum(trivy_resource_configaudits{namespace=~\"$Entorno\",severity=\"Unknown\"}) or on() vector(0)",
       "legendFormat": "Unknown"
      }
     ]
    },
    {
     "title": "Security Missconfigurations",
     "type": "table",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 127 },
     "targets": [
      {
       "expr": "trivy_configaudits_info{namespace=~\"$Entorno\",severity=~\"$Severity\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  {
   "title": "RBAC Assessment",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Severity Breakdown of RBAC Security Issues",
     "type": "stat",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(trivy_role_rbacassessments{namespace=~\"$Entorno\",severity=\"Critical\"}) or on() vector(0)",
       "legendFormat": "Critical"
      },
      {
       "expr": "sum(trivy_role_rbacassessments{namespace=~\"$Entorno\",severity=\"High\"}) or on() vector(0)",
       "legendFormat": "High"
      },
      {
       "expr": "sum(trivy_role_rbacassessments{namespace=~\"$Entorno\",severity=\"Medium\"}) or on() vector(0)",
       "legendFormat": "Medium"
      },
      {
       "expr": "sum(trivy_role_rbacassessments{namespace=~\"$Entorno\",severity=\"Low\"}) or on() vector(0)",
       "legendFormat": "Low"
      },
      {
       "expr": "sum(trivy_role_rbacassessments{namespace=~\"$Entorno\",severity=\"UNKNOWN\"}) or on() vector(0)",
       "legendFormat": "Unknown"
      }
     ]
    },
    {
     "title": "Permission Issues",
     "type": "table",
     "gridPos": { "h": 11, "w": 24, "x": 0, "y": 128 },
     "targets": [
      {
       "expr": "trivy_rbacassessments_info{namespace=~\"$Entorno\",severity=~\"$Severity\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  },
  { "title": "InfraAssessment", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 } },
  {
   "title": "Severity Breakdown of all InfraAssessments",
   "type": "stat",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(trivy_infraassessments_info{namespace=~\"$Entorno\",severity=\"Critical\"})",
     "legendFormat": "Critical"
    },
    {
     "expr": "count(trivy_infraassessments_info{namespace=~\"$Entorno\",severity=\"High\"})",
     "legendFormat": "High"
    },
    {
     "expr": "count(trivy_infraassessments_info{namespace=~\"$Entorno\",severity=\"Medium\"})",
     "legendFormat": "Medium"
    },
    {
     "expr": "count(trivy_infraassessments_info{namespace=~\"$Entorno\",severity=\"Low\"}) or on() vector(0)",
     "legendFormat": "Low"
    },
    {
     "expr": "count(trivy_infraassessments_info{namespace=~\"$Entorno\",severity=\"Unknown\"})or on() vector(0)",
     "legendFormat": "Unknown"
    }
   ]
  },
  {
   "title": "Infra Security Issues",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "trivy_infraassessments_info{namespace=~\"$Entorno\",severity=~\"$Severity\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Exposed Secrets",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 21 },
   "collapsed": true,
   "panels": [
    {
     "title": "Severity Breakdown of all Exposed Secrets",
     "type": "stat",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 61 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(trivy_image_exposedsecrets{severity=\"Critical\",namespace=~\"$Entorno\"}) or on() vector(0)",
       "legendFormat": "Critical"
      },
      {
       "expr": "sum(trivy_image_exposedsecrets{severity=\"High\",namespace=~\"$Entorno\"}) or on() vector(0)",
       "legendFormat": "High"
      },
      {
       "expr": "sum(trivy_image_exposedsecrets{severity=\"Medium\",namespace=~\"$Entorno\"}) or on() vector(0)",
       "legendFormat": "Medium"
      },
      {
       "expr": "sum(trivy_image_exposedsecrets{severity=\"Low\",namespace=~\"$Entorno\"}) or on() vector(0)",
       "legendFormat": "Low"
      },
      {
       "expr": "sum(trivy_image_exposedsecrets{severity=\"Unknown\",namespace=~\"$Entorno\"}) or on() vector(0)",
       "legendFormat": "Unknown"
      }
     ]
    },
    {
     "title": "Exposed Secrets per namespace",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 68 },
     "targets": [
      {
       "expr": "sum(trivy_image_exposedsecrets {namespace=~\"$Entorno\",severity=~\"$Severity\"} ) by (namespace)",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Exposed Secrets Findings",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 76 },
     "targets": [
      {
       "expr": "sum by (namespace, image_registry, image_repository, image_tag, resource_kind, resource_name, container_name, secret_category, secret_title, secret_target, severity) (trivy_exposedsecrets_info{namespace=~\"$Entorno\", severity=~\"$Severity\"})",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}