alertmanager:
  enabled: false

grafana:
  enabled: true
  admin:
    existingSecret: monitoring-grafana-admin
    userKey: admin-user
    passwordKey: admin-password

prometheus:
  enabled: true

prometheusOperator:
  enabled: true

kubeStateMetrics:
  enabled: true

nodeExporter:
  enabled: true
