apiVersion: apps/v1
kind: Deployment
metadata:
  name: secure-kube-ops
  labels:
    app: secure-kube-ops
spec:
  replicas: 1
  selector:
    matchLabels:
      app: secure-kube-ops
  template:
    metadata:
      labels:
        app: secure-kube-ops
    spec:
      imagePullSecrets:
        - name: ghcr-pull-secret
      containers:
        - name: secure-kube-ops-api
          image: ghcr.io/zinedinealvarez/secure-kube-ops:0d3414a6a6aa916eb1daa21c55094c459c472e28
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
