apiVersion: v1
kind: Namespace
metadata:
  name: runtime-security
  labels:
    app.kubernetes.io/name: runtime-security
    app.kubernetes.io/part-of: secure-kube-ops
    securekubeops.io/purpose: runtime-security
