name: DevSecOps Pipeline

on:
  push:
  pull_request:

jobs:
  docker-build:
    name: Build Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t secure-cicd-kubernetes:ci .
