name: DevSecOps Pipeline

on:
  push:
  pull_request:

jobs:
  docker-build:
    name: Build and scan Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t secure-cicd-kubernetes:${{ github.sha }} .

      - name: Informational Trivy scan
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: image
          image-ref: secure-cicd-kubernetes:${{ github.sha }}
          scanners: vuln
          format: table
          exit-code: 0
          ignore-unfixed: true
          vuln-type: os,library
          severity: UNKNOWN,LOW,MEDIUM,HIGH,CRITICAL

      - name: Trivy Security Gate
        uses: aquasecurity/trivy-action@v0.36.0
        with:
          scan-type: image
          image-ref: secure-cicd-kubernetes:${{ github.sha }}
          scanners: vuln
          format: table
          exit-code: 1
          ignore-unfixed: true
          vuln-type: os,library
          severity: HIGH,CRITICAL
